= Dokumentation

== Websockets

=== Referenz

* https://quarkus.io/guides/websockets

=== Dependencies

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-websockets</artifactId>
</dependency>
----

=== Was sind Websockets
* Eine dauerhafte Verbindung zwischen Server und Client
* Man kann mit http Daten vom Server zum Client schicken

=== Umsetzung im Mikroprojekt
Sind in meinem Projekt als ChatSocket eingebaut.
Dafür wurde tutorial von der Quarkus.io Website verwendet.
Idee liegt darin, dass Personen fragen wegen der Tanztermine, Tanzkurse, ... stellen können.


== GraphQL

=== Referenz

* https://quarkus.io/guides/smallrye-graphql

=== Dependencies

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-graphql</artifactId>
</dependency>
----

=== Was ist GraphQL
Es ist eine Abfragesprache. Man erhält nur die Daten, welche man wirklich braucht und möchte.
Durch GraphQL werden APIs schneller und auch flexibler.

=== Umsetzung im Übungsrepository
https://github.com/2122-4ahif-nvs/04-lab-graphql-HautzmayerSheila

=== Umsetzung im Mikroprojekt
<1> @GraphQLApi muss über der Klasse hinzugefügt werden.
<2> Bei der findAll() Methode wird @Query(...) hinzugefügt um später darauf zugreifen zu können.

.boundary/PersonResource.java
[source, java]
----
@GraphQLApi <1>
@Path("/Person")
public class PersonResource {
    @ConfigProperty(name = "greeting", defaultValue = "hi")
    String greeting;

    @Inject
    Logger logger;

    @Inject
    PersonRepository personRepository;

    @Inject
    CourseRepository courseRepository;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Query("allPeople") <2>
    public List<Person> findAll() {
        return personRepository.findAll();
    }

----
Aufruf findet dann auf dem GraphQL Server mit folgendem statt.

[source,java]
----
query allPeople {
allPeople {
firstName,
lastName
}
}

----




== Validation

=== Referenz

* https://quarkus.io/guides/validation

=== Dependencies

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-validator</artifactId>
</dependency>
----


=== Was ist Validation

Durch Validation werden bestimmte Regeln befolgt. Beispielsweise ob ein Feld einer bestimmten Größe haben oder nicht leer sein dürfen.

=== Umsetzung im ÜbungsRepository

https://github.com/2122-4ahif-nvs/05-validation-qute-HautzmayerSheila

=== Umsetzung im Mikroprojekt

==== Validierung in Klasse Course

<1> Validierung über das zu validierende Feld schreiben

.entity/Course.java
[source, java]
----

@Entity
public class Course {
@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
private String name;

    @NotBlank(message="Name must not be blank") <1>
    private String name;

    @Min(message="Course has too less people", value=1) <1>
    private int maxNumberOfPeople;
    @NotBlank(message="Description must not be blank") <1>
    private String description;

----

==== Validierung beim Endpoint

<1> Klasse Result hinzufügen
<2> @Valid wird bei der Parametergabe verwendet

.boundary/CourseResource.java
[source, java]
----
@Path("/end-point-method-validation")
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Result tryMeEndPointMethodValidation(@Valid Course course) { <2>
return new Result("Course is valid! It was validated by end point method validation.");
}

public static class Result {  <1>

        private String message;
        private boolean success;

        Result(String message) {
            this.success = true;
            this.message = message;
        }

        Result(Set<? extends ConstraintViolation<?>> violations) {
            this.success = false;
            this.message = violations.stream()
                    .map(cv -> cv.getMessage())
                    .collect(Collectors.joining(", "));
        }

        public String getMessage() {
            return message;
        }

        public boolean isSuccess() {
            return success;
        }

    }
----

==== Validierung im Repository

<1> Aufruf der Methode im Repo.
<2> @Valid Annotation direkt in der Methode im Repo hinzufügen

.boundary/CourseResource.java
[source, java]
----
@Path("/repo-method-validation")
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Result tryMeServiceMethodValidation(Course course) {
try {
courseRepository.validateCourse(course); <1>
return new Result("Course is valid! It was validated by service method validation.");
} catch (ConstraintViolationException e) {
return new Result(e.getConstraintViolations());
}
}
----

.control/CourseRepository.java
[source,java]
----
public void addCourse(@Valid Course course) { <2>
this.save(course);
}
----


== Qute

=== Referenz

* https://quarkus.io/guides/qute

=== Dependencies

[source,xml]
----
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-resteasy-qute</artifactId>
</dependency>
----


=== Was ist Qute
Es wird eine Art von FrontEnd erstellt.
Man kann zur Laufzeit den Aufbau von Objekten sehen.
Es wird die reflection durch die verringerung von ger Größe von native images minimiert.

=== Umsetzung im ÜbungsRepository
https://github.com/2122-4ahif-nvs/05-validation-qute-HautzmayerSheila

=== Umsetzung im Mikroprojekt

<1> Simples Template im Pfad /src/main/resources/templates/ItemResource/hello.txt

[source,text]
----
Welcome to the dance studio {name}!
----


<1> Eine HelloResource ist geadded worden.
<2> Template wird erzeugt
<3> Neue Template Instanz wird zurückgegeben.

.boundary/HelloResource.java
[source,java]
----
@Path("hello")
public class HelloResource { <1>

    @CheckedTemplate
    public static class Templates { <2>
        public static native TemplateInstance hello(String name);
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public TemplateInstance get(@QueryParam("name") String name) {
        return Templates.hello(name); <3>
    }
}

----

== GRPC

=== Referenz

* https://quarkus.io/guides/grpc-getting-started

=== Dependencies

[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-grpc</artifactId>
</dependency>
----

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-reactive</artifactId>
</dependency>
----

=== Was ist GRPC
Google Remote Procedure Call
Für Microservices ist die Performance besser als bei der Verwendung von Rest.

=== Umsetzung in Mikroprojekt

<1> In Directory /src/main/proto wird folgendes helloworld.proto file erzeugt

[source,prototext]
----
syntax = "proto3"; <1>

option java_multiple_files = true;
option java_package = "io.quarkus.example";
option java_outer_classname = "HelloWorldProto";

package helloworld;

// The greeting service definition.
service Greeter {
// Sends a greeting
rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
string name = 1;
}

// The response message containing the greetings
message HelloReply {
string message = 1;
}
----

Um die Klassen für die Verwendung von GRPC zu generieren muss man

[source, text]
----
mvn compile
----

im Terminal ausführen.

<1> Service für GRPC wird implementiert
<2> @GrpcService wird injected
<3> Das Service Interface Greeter wird implementiert
<4> Methode um hello zurückzuliefern wird hinzugefügt

.control/HelloWorldRepository
[source,java]
----
<1>
@GrpcService <2>
public class HelloWorldRepository implements Greeter { <3>

    @Override
    public Uni<HelloReply> sayHello(HelloRequest request) { <4>
        return Uni.createFrom().item(() ->
                HelloReply.newBuilder().setMessage("Hello " + request.getName()).build()
        );
    }
}
----

<1> Resource wird implementiert
<2> @GRPCClient wird injected

.boundary/HelloWorldResource
[source, java]
----
<1>
@Path("/hello")
public class HelloWorldResource {

    @GrpcClient <2>
    Greeter hello;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }

    @GET
    @Path("/{name}")
    public Uni<String> hello(@PathParam("name") String name) {
        return hello.sayHello(HelloRequest.newBuilder().setName(name).build())
                .onItem().transform(helloReply -> helloReply.getMessage());
    }
}
----

== Security mit .properties Files

=== Referenz

* https://quarkus.io/guides/security-properties

=== Dependencies

[source,xml]
----
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-elytron-security-properties-file</artifactId>
</dependency>
----

=== Was machen .Properties Files für Security
Bei der Properties Files Realm Configuration wird das mapping von Usern mit Passwörtern und Usern mit Rollen ermöglicht.

=== Umsetzung im Mikroprojekt

* https://2122-4ahif-nvs.github.io/01-microproject-HautzmayerSheila/documentationProp.html


== Security in JPA

=== Referenz

* https://quarkus.io/guides/security-jpa


=== Dependencies

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-security-jpa</artifactId>
</dependency>
----

=== Was macht Security für JPA

Zugriffskontrollen und das Ausfiltern in der Datenbank wird mit Annotationen umgesetzt.
Dadurch werden nicht erlaubte Daten nicht unnötig geladen und Teile von sicherheitsrelevantem Code können eliminiert werden.
Vorteile sind dadurch geringerer Ressourcenverbrauch, weniger Code-Duplikationen und Erleichterung der Les- und Wartbarkeit.


=== Umsetzung im ÜbungsRepository

* https://2122-4ahif-nvs.github.io/01-microproject-HautzmayerSheila/documentationSec.html

=== Umsetzung im Mikroprojekt

Am branch security-jpa. Fast genau selber Vorgang wie im Übungsrepository. Doku ist beim oberen Link nachzulesen.
Einziger Unterschied -> Nur eine Resource (SecurityResource) für Endpoints für Public, Admin und User.
