@startuml
'https://plantuml.com/class-diagram


class Raum{
    -termin: Termin
    -raumNummer: Long
}


class Kurs{
    -termin: Termin
    -beschreibung: String
    -name: String
}

class Kurseinteilung{
    -kurs: Kurs
    -person: Person
}

class Person{
    -vorname: string
    -nachname: string
}

class Termin{
    -von: DateTime
    -bis: DateTime
}


Kurs "*" -- "*" Person
Termin "*" -- "1" Kurs
Termin "*" -l- "1" Raum

(Kurs, Person) .. Kurseinteilung




@enduml