@startuml
'https://plantuml.com/class-diagram


class Raum{

}

class Tänzer{

}

class Kurs{
    -raum: Raum
}

class Stundenplan{
    -kurs: Kurs
    -trainer: Trainer
    -tänzer: Tänzer
}

class Trainer{

}




Kurs "*" -l-> "1" Raum
Kurs "*" -- "*" Trainer
Kurs "*" -l- "*" Tänzer

(Kurs, Trainer) .. Stundenplan
(Kurs, Tänzer) .. Stundenplan


@enduml