@startuml
'https://plantuml.com/class-diagram


class Raum{

}

class Tänzer{

}

class Tanzstunde{
    -raum: Raum
}

class Stundenplan{
    -tanzstunde: Tanzstunde
    -person: Person
}

class Trainer{

}
class Person{
    -vorname: string
    -nachname: string
}




Tanzstunde "*" -r-> "1" Raum
Tanzstunde "*" -- "*" Person

(Tanzstunde, Person) .. Stundenplan


Person <|-- Tänzer
Person <|-- Trainer

@enduml